import { defineConfig } from 'cspell';

export default defineConfig({
  version: '0.2',
  ignoreWords: [
    'fontsource',
    'hanken',
    'wght',
    'mayes',
    'nums',
    'litert',
    'jsonrepair',
    'litertlm',
    'dexie',
    'ngsw',
    'Lemmatizer',
    'viewports',
    'grotesk',
    'wayfinder',
    'huggingface',
    'OPFS',
    'Wayfinding',
    'subcomponents',
    'precomputation',
    'reprime',
    'microtasks',
    'ttfb',
    'roundtrips',
    'glassmorphic',
    'sandboxed',
    'multimodal',
    'Tesseract',
    'sandboxed',
    'coep',
  ],
  ignorePaths: [
    'node_modules',
    'dist',
    'coverage',
    '.git',
    '.vscode',
    '.idea',
    '*.spec.ts',
    'firebase.config.json',
    'ngsw-config.json',
    'firebase.config',
    'skills-lock.json',
    'stemmer.ts',
  ],
});
