export const TOXIC_WORDS = ['hate', 'kill', 'abuse', 'hateful', 'toxic', 'dumb', 'stupid', 'idiot'];

export const FINANCE_KEYWORDS = [
  'expense',
  'spending',
  'spent',
  'cost',
  'buy',
  'bought',
  'transaction',
  'purchase',
  'ledger',
  'money',
  'budget',
  'insights',
  'total',
  'average',
  'highest',
  'lowest',
  'dining',
  'cloud',
  'office',
  'category',
  'merchant',
  'how much',
  'what is',
  'show',
  'list',
  'analyze',
  'summarize',
  'gemma',
];
